name: CI - BBE Load Board

on:
  push:
    branches: [ main ]
    paths:
      - "app.py"
      - "requirements.txt"
      - "runtime.txt"
      - ".streamlit/**"
      - "zip_db.csv"
      - "sample_loads.csv"
      - "brokers.csv"
      - ".github/workflows/ci.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sanity import check
        run: |
          python - << 'PY'
          import streamlit, pandas, numpy, pydeck
          print("✅ Imports:", streamlit.__version__, pandas.__version__, numpy.__version__, pydeck.__version__)
          PY

      - name: Wake Streamlit app
        env:
          APP_URL: ${{ secrets.STREAMLIT_APP_URL }}
        run: |
          curl -L --max-time 20 "${APP_URL:-https://bbe-load-board.streamlit.app/}" || true
